version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/assignment/mongo-data:/data/db
    networks:
      - assignment

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./src
        target: /app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongodb:27017/assignment
      - ACCESS_KEY_JWT_SECRET=access_key_secret
      - REFRESH_KEY_JWT_SECRET=refresh_key_secret
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - assignment

networks:
  assignment:
